project:
  type: website

website:
  title: "Unlocking Data<br /><span style='font-size: 0.8em;'>A Gentle Introduction to APIs</span><br />"
  site-url: "https://ucsb-library-research-data-services.github.io/intro2APIs/"
  page-navigation: true
  page-footer:
    background: "#003660"
    left: |
      <img src="https://raw.githubusercontent.com/UCSB-Library-Research-Data-Services/rds-ws-catalogue/refs/heads/main/assets/imgs/HexSticker-RDS.png" alt="UCSB Library Research Data Services logo" class="footer-badge"/>
    center: |
      <strong>UCSB Library Research Data Services</strong>
      
      <a href="https://creativecommons.org/licenses/by-nc/4.0/deed.en" class="footer-cc-license">
        <img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="CC" class="cc-icon"/>
        <img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="BY" class="cc-icon"/>
        <img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="NC" class="cc-icon"/>
      </a>
      
      <a href="https://doi.org/10.5281/zenodo.15015037" class="footer-doi-badge">
        <img src="https://zenodo.org/badge/DOI/10.5281/zenodo.15015037.svg" alt="DOI"/>
      </a>
    right: |
      <div class="footer-tech">
        <a class="footer-tech-item" href="https://quarto.org/">
          <img src="/_static/imgs/quarto-no-official.svg" alt="Quarto" class="footer-tech-icon"/>
          Quarto
        </a>
        <a class="footer-tech-item" href="https://github.com/UCSB-Library-Research-Data-Services/intro2APIs">
          <i class="bi bi-github footer-tech-icon" aria-hidden="true"></i>
          GitHub
        </a>
      </div>
  sidebar:
    collapse-level: 1
    style: "docked"
    background: "#ede9e1"
    search: true
    header: |
      ![<a href="https://www.flaticon.com/free-icons/api" title="api icons" target="_blank" class="header-icon-attribution">Api icons created by HAJICON - Flaticon</a>](/_static/imgs/integration.png)
    
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: What are APIs and why do they exists
        href: chapters/what-is-an-api.qmd
      - section: Interacting with APIs
        contents:
          - text: "Endpoints"
            href: chapters/interactingAPIs/endpoints.qmd
          - text: "Request Methods"
            href: chapters/interactingAPIs/request-methods.qmd
          - text: "Interacting with APIs"
            href: chapters/interactingAPIs/interact-apis.qmd
          - text: "Exercise: Calling Data"
            href: chapters/interactingAPIs/exercise-calling-data.qmd
      - section: Interacting with APIs using Postman
        contents:
          - text: "Postman"
            href: chapters/postman/postman.qmd
          - text: "Basic Request"
            href: chapters/postman/postman-basic-requests.qmd
          - text: "Environment Variables"
            href: chapters/postman/postman-environment.qmd
          - text: "POST Requests in Postman"
            href: chapters/postman/postman-post.qmd
          - text: "DELETE Requests in Postman"
            href: chapters/postman/postman-delete.qmd
          - section: "Exercise: The GitHub API"
            contents:
              - text: "Working with the GitHub API"
                href: chapters/postman/exercise-github-api.qmd
              - text: "Exercise 1: Getting Information from GitHub"
                href: chapters/postman/exercise-github-api-1.qmd
              - text: "Exercise 2: Adding and Removing Information from GitHub"
                href: chapters/postman/exercise-github-api-2.qmd
      - section: "Getting Data Programmatically"
        contents:
          - text: "Interacting with APIs with Python"
            href: chapters/python/python.qmd
      - section: "APIs for Data Analysis"
        contents:
          - text: "Collecting Data for Analysis"
            href: chapters/dataAnalysis/collecting-data-for-analysis.qmd
          - text: "Analyzing Data"
            href: chapters/dataAnalysis/analyzing-data.qmd
      - text: "A Catalog of APIs"
        href: resources/catalog.qmd
  google-analytics: G-VR8KJJEZHW

format:
  html:
    theme:
      - united
      - _static/css/styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito

execute:
  freeze: auto

